
export { default as App} from './App.jsx';
export { InicioSesionPage } from './pages/inicio_sesion.jsx';
export { RegistroPage } from './pages/Registro.jsx';
export { EditarPerfilUsuarioPage } from './pages/editar_perfil_usuario';
export { OlvidopassonePage } from './pages/olvido_contrase1';
export { OlvidopasstwoPage } from './pages/olvido_contrase2';
export { OlvidopasstreePage } from './pages/olvido_contrase3';
export { FincaPage } from './pages/fincas';
export { UsuarioPage } from './pages/Usuarios';
export { VariedadPage } from './pages/Variedad';
export { CultivosPage } from './pages/cultivos';
export { ActividadPage } from './pages/Actividades.jsx';
export { LotesPage } from './pages/Lotes.jsx';
export { RecursosPage } from './pages/Recursos.jsx';
export { SoportePage } from './pages/Soporte.jsx';
export { DashboardPage } from './pages/dashboar';
export { ReportesPage } from './pages/Reportes.jsx';
export { ProgramacionPage } from './pages/Programacion.jsx';
export { ProduccionPage } from './pages/Produccion.jsx';
export { PerfilprincipalPage } from './pages/Perfil.jsx';
